TVendo.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TVendo.Web.Data;
using TVendo.Web.Data.Entities;
using TVendo.Web.Models;

namespace TVendo.Web.Controllers
{
    [Authorize(Roles = "Developer")]
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository categoryRepository;

        public CategoriesController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        // GET: Categories
        public IActionResult Index()
        {
            return View(categoryRepository.GetAll());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await categoryRepository.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryViewModel view)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData  = null;
                string path = null;

                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.svg";
                    path = file;

                    using (var ms = new MemoryStream())
                    {
                        await view.ImageFile.CopyToAsync(ms);
                        var fileBytes = ms.ToArray();
                        imageData = fileBytes;
                    }

                }

                var category = new Category { Id = view.Id, Name = view.Name };
                await categoryRepository.CreateAsync(category, imageData, path);
                return RedirectToAction(nameof(Index));
            }
            return View(view);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await categoryRepository.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }
            var categoryViewModel = new CategoryViewModel { Id = category.Id, Name = category.Name, IconImageUrl = category.IconImageUrl };
            return View(categoryViewModel);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CategoryViewModel view)
        {
            if (id != view.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string path = null;
                byte[] imageData = null;


                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.svg";
                    path = file;

                    using (var ms = new MemoryStream())
                    {
                        await view.ImageFile.CopyToAsync(ms);
                        var fileBytes = ms.ToArray();
                        imageData = fileBytes;
                    }
                }

                var category = new Category { IconImageUrl = view.IconImageUrl, Id = view.Id, Name = view.Name };

                try
                {
                    await categoryRepository.UpdateAsync(category, imageData, path);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await CategoryExistsAsync(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(view);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await categoryRepository.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await categoryRepository.GetByIdAsync(id);
            await categoryRepository.DeleteAsync(category);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> CategoryExistsAsync(int id)
        {
            return await categoryRepository.ExistAsync(id);
        }
    }
}

TVendo.Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TVendo.Web.Data;
using TVendo.Web.Data.Entities;
using TVendo.Web.Data.Repositories;

namespace TVendo.Web.Controllers
{
    [Authorize(Roles = "Developer")]
    public class MessagesController : Controller
    {
        private readonly IMessageRepository messageRepository;

        public MessagesController(IMessageRepository messageRepository)
        {
            this.messageRepository = messageRepository;
        }

        // GET: Messages
        public IActionResult Index()
        {
            return View(messageRepository.GetAllWithUsers());
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await messageRepository.GetByIdAsync(id.Value);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            ViewData["SourceUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName");
            ViewData["TargetUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName");
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Message message)
        {
            message.SentDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                await messageRepository.CreateAsync(message);
                return RedirectToAction(nameof(Index));
            }
            ViewData["SourceUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName", message.SourceUserId);
            ViewData["TargetUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName", message.TargetUserId);
            return View(message);
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await messageRepository.GetByIdAsync(id.Value);
            if (message == null)
            {
                return NotFound();
            }
            ViewData["SourceUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName", message.SourceUserId);
            ViewData["TargetUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName", message.TargetUserId);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TargetUserId,SourceUserId,Text,SentDate")] Message message)
        {
            if (id != message.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await messageRepository.UpdateAsync(message);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await MessageExistsAsync(message.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SourceUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName", message.SourceUserId);
            ViewData["TargetUserId"] = new SelectList(messageRepository.GetUsers(), "Id", "UserName", message.TargetUserId);
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await messageRepository.GetAllWithUsers().FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await messageRepository.GetByIdAsync(id);
            await messageRepository.DeleteAsync(message);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MessageExistsAsync(int id)
        {
            return await messageRepository.ExistAsync(id);
        }
    }
}

TVendo.Web/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TVendo.Web.Data;
using TVendo.Web.Data.Entities;

namespace TVendo.Web.Controllers
{
    [Authorize(Roles = "Developer")]
    public class TagsController : Controller
    {
        private readonly ITagRepository repository;

        public TagsController(ITagRepository repository)
        {
            this.repository = repository;
        }

        // GET: Tags
        public IActionResult Index()
        {
            return View(repository.GetAll());
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await repository.GetByIdAsync(id.Value);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                await repository.CreateAsync(tag);
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await repository.GetByIdAsync(id.Value);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await repository.UpdateAsync(tag);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await TagExistsAsync(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await repository.GetByIdAsync(id.Value);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tag = await repository.GetByIdAsync(id);
            await repository.DeleteAsync(tag);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> TagExistsAsync(int id)
        {
            return await repository.ExistAsync(id);
        }
    }
}

TVendo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TVendo Admin Site</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/w3schools.css" />
        <link rel="stylesheet" href="~/node_modules/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/w3schools.css" />
        <link rel="stylesheet" href="~/node_modules/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sitio de Administración</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Productos</a></li>
                    <li><a asp-area="" asp-controller="Tags" asp-action="Index">Tags</a></li>
                    <li><a asp-area="" asp-controller="ProductTags" asp-action="Index">Tags de Productos</a></li>
                    <li><a asp-area="" asp-controller="TagIncompatibilities" asp-action="Index">Incompatibilidad de Tags</a></li>
                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categorias</a></li>
                    <li><a asp-area="" asp-controller="Subcategories" asp-action="Index">Subcategorias</a></li>
                    <li><a asp-area="" asp-controller="Messages" asp-action="Index">Mensajes</a></li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        if (this.User.IsInRole("Admin") || this.User.IsInRole("Developer"))
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="Index">Usuarios</a></li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - TVendo.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>